spring:
  profiles:
    active: prod

  datasource:
    druid: #连接池信息
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000





mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  typeAliasesPackage: com.coco.tango.surfing.core.dal.domain
  global-config:
    db-config:
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql





tango:
  filter:
    allow-urls: /login/wx