spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tango_surfing?autoReconnect=true&characterEncoding=utf-8
    username: root
    password: admin123



wx:
  app-id: wx80419bbfd8d360eb
  secret: b668a4735a2b61dc800dfc61f539487c

